POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZG9uZTIiLCJpZCI6IjVmN2MyMzljNGI1MTVlMDk0ODEzM2YxMyIsImlhdCI6MTYwMTk3NTg0OH0.lVsMqLNoJSYDnvL9h4l-t00B4Ssn5_Lsd56ARolUu8k

{
  "title":"!!!!!!!Blog to DELETE",
  "author":"random guy",
  "url":"none-one",
  "likes": 5
}